/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.arduinoshop.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.arduinoshop.controller.UserController;
import lk.arduinoshop.model.UserDTO;
import lk.arduinoshop.model.UserPrivilegeDTO;
import lk.arduinoshop.util.HashUtil;
import repository.UserRepository;

/**
 *
 * @author Iyona Chithrasena
 */
public class UsersPanel extends javax.swing.JPanel {

    private List<UserDTO> allUsers;

    /**
     * Creates new form testpanel
     */
    public UsersPanel() {
        initComponents();
        //----- initially set 2 default list model
        allPrivilegesList.setModel(new DefaultListModel());
        selectedPrivilegesLiast.setModel(new DefaultListModel());

        loadUsersAndPrivileges();
        loadAllPrivileges();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProductSummery = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        useNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        rePasswordField = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        selectedPrivilegesLiast = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        allPrivilegesList = new javax.swing.JList<>();
        shiftButton = new javax.swing.JButton();
        shiftButton1 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUserNameList = new javax.swing.JTable();
        jButtonDeleteUserDetailPanel = new javax.swing.JButton();
        jButtonResetPasswordUserDetailPanel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelProductSummery.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProductSummery.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("User Name");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Re Enter Password");

        useNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(51, 0, 204));
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("Add user");

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        rePasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("All Privileges");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setText("Selected Privileges");

        selectedPrivilegesLiast.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(selectedPrivilegesLiast);

        allPrivilegesList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(allPrivilegesList);

        shiftButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        shiftButton.setText(">");
        shiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftButtonActionPerformed(evt);
            }
        });

        shiftButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        shiftButton1.setText("<");
        shiftButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftButton1ActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProductSummeryLayout = new javax.swing.GroupLayout(jPanelProductSummery);
        jPanelProductSummery.setLayout(jPanelProductSummeryLayout);
        jPanelProductSummeryLayout.setHorizontalGroup(
            jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductSummeryLayout.createSequentialGroup()
                .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductSummeryLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProductSummeryLayout.createSequentialGroup()
                                .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(shiftButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(shiftButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelProductSummeryLayout.createSequentialGroup()
                                .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(useNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rePasswordField)))))
                    .addGroup(jPanelProductSummeryLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanelProductSummeryLayout.setVerticalGroup(
            jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductSummeryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductSummeryLayout.createSequentialGroup()
                        .addComponent(useNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProductSummeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProductSummeryLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(shiftButton)
                        .addGap(18, 18, 18)
                        .addComponent(shiftButton1)))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("User details");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setBackground(new java.awt.Color(51, 0, 204));
        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setText("User Name List");

        tableUserNameList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserId", "User Name", "State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableUserNameList);

        jButtonDeleteUserDetailPanel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButtonDeleteUserDetailPanel.setText("Delete");
        jButtonDeleteUserDetailPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserDetailPanelActionPerformed(evt);
            }
        });

        jButtonResetPasswordUserDetailPanel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButtonResetPasswordUserDetailPanel.setText("Reset Password");
        jButtonResetPasswordUserDetailPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetPasswordUserDetailPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonResetPasswordUserDetailPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDeleteUserDetailPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButtonDeleteUserDetailPanel)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonResetPasswordUserDetailPanel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelProductSummery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProductSummery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteUserDetailPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserDetailPanelActionPerformed
        int row = tableUserNameList.getSelectedRow();
        
        //if(row) {
            
       // }
        
        
        int userId = (Integer) tableUserNameList.getModel().getValueAt(row, 0);
        boolean isUserDeleted = UserController.softDeleteUser(userId);
        
        loadUsersAndPrivileges();
        
        
    }//GEN-LAST:event_jButtonDeleteUserDetailPanelActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
//        String error = "Are you want sure to change password?";
//        JTextArea outputArea = new JTextArea(12,10);
//        outputArea.setText(error);
//        JOptionPane.showMessageDialog(null, error,"Confirmation Message", JOptionPane.QUESTION_MESSAGE);// TODO add your handling code here:
        // ----- Check password Correct
        String userName = useNameTextField.getText();
        String password = new String(passwordField.getPassword());
        String rePassword = new String(rePasswordField.getPassword());

        for (UserDTO userDTO : allUsers) {
            if (userDTO.getUserName().equals(userName)) {
                String error = "User name already exist ! Please use another user Name.";
                JOptionPane.showMessageDialog(this, error, "User Exist", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        if (!password.equals(rePassword)) {
            String error = "Re-Enter password not matched.";
            JOptionPane.showMessageDialog(this, error, "Password Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(selectedPrivilegesLiast.getModel().getSize() < 1) {
            String error = "You need to select at least 1 privilege for the user.";
            JOptionPane.showMessageDialog(this, error, "Privilege Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ------- Create userDto
        UserDTO userDTO = new UserDTO();
        userDTO.setUserName(useNameTextField.getText());
        userDTO.setPassword(HashUtil.convertToHash(password));
        userDTO.setUserStatus("NEW");

        // -------- Add privilage to userDTO
        List<UserPrivilegeDTO> userPrivilegeList = new ArrayList<>();

        int maxId = UserController.maxID();
        for (int i = 0; i < selectedPrivilegesLiast.getModel().getSize(); i++) {
            String item = selectedPrivilegesLiast.getModel().getElementAt(i);
            UserPrivilegeDTO userPrivilegeDTO = new UserPrivilegeDTO();
            userPrivilegeDTO.setPrivilege(item);
            userPrivilegeDTO.setId(maxId);
            userPrivilegeList.add(userPrivilegeDTO);

            userDTO.setUserPrivilage(userPrivilegeList);
        }

        // ------ user and privilege
        boolean userAdded = UserController.addUserWithPrivilege(userDTO);

        // ---- refresh loadUsersAndPrivileges() 
        loadUsersAndPrivileges();

        // ----- clear fields 
        clearPanelData();

    }//GEN-LAST:event_saveButtonActionPerformed

    private void shiftButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftButton1ActionPerformed
        DefaultListModel selectedPrivilegesLiastModel = (DefaultListModel) selectedPrivilegesLiast.getModel(); // selectedPrivilegesLiastModel
        String selectedValue = selectedPrivilegesLiast.getSelectedValue();

        DefaultListModel allPrivilegesListModel = (DefaultListModel) allPrivilegesList.getModel(); //allPrivilegesListModel
        allPrivilegesListModel.addElement(selectedValue);
        allPrivilegesList.setModel(allPrivilegesListModel);

        selectedPrivilegesLiastModel.removeElement(selectedValue);
    }//GEN-LAST:event_shiftButton1ActionPerformed

    private void shiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftButtonActionPerformed

        DefaultListModel allPrivilegesListModel = (DefaultListModel) allPrivilegesList.getModel();
        String selectedValue = allPrivilegesList.getSelectedValue();

        DefaultListModel selectedPrivilegesLiastModel = (DefaultListModel) selectedPrivilegesLiast.getModel();
        selectedPrivilegesLiastModel.addElement(selectedValue);
        selectedPrivilegesLiast.setModel(selectedPrivilegesLiastModel);

        allPrivilegesListModel.removeElement(selectedValue);


    }//GEN-LAST:event_shiftButtonActionPerformed

    private void jButtonResetPasswordUserDetailPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetPasswordUserDetailPanelActionPerformed
        
        DefaultTableModel defaultTableModel = (DefaultTableModel) tableUserNameList.getModel();
        int selectedRow = tableUserNameList.getSelectedRow();
        if( selectedRow == -1) {
            return;
        }
        
        int userId = Integer.parseInt(defaultTableModel.getValueAt(selectedRow, 0).toString());
        String status = defaultTableModel.getValueAt(selectedRow, 2).toString();
        
         if( status.equals("NEW") || status.equals("NEW") ) {
            return;
        }
        
        String password = JOptionPane.showInputDialog("Please Enter Default Password to re-set Password ");
        
        UserDTO userDTO = new UserDTO();
        password = HashUtil.convertToHash(password);
        userDTO.setPassword(password);
        userDTO.setUserId(userId);
        userDTO.setUserStatus("NEW");
        
        boolean status1 = UserController.resetUser(userDTO);
        loadUsersAndPrivileges();
        
    }//GEN-LAST:event_jButtonResetPasswordUserDetailPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> allPrivilegesList;
    private javax.swing.JButton jButtonDeleteUserDetailPanel;
    private javax.swing.JButton jButtonResetPasswordUserDetailPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelProductSummery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField rePasswordField;
    private javax.swing.JButton saveButton;
    private javax.swing.JList<String> selectedPrivilegesLiast;
    private javax.swing.JButton shiftButton;
    private javax.swing.JButton shiftButton1;
    private javax.swing.JTable tableUserNameList;
    private javax.swing.JTextField useNameTextField;
    // End of variables declaration//GEN-END:variables

    private void loadUsersAndPrivileges() {

        allUsers = UserController.allUsers();

        // ---- Set data to user list table
        DefaultTableModel tableModel = (DefaultTableModel) tableUserNameList.getModel();
        tableModel.setRowCount(0);

        for (UserDTO userDTO : allUsers) {
            Object[] row = new Object[3];
            row[1] = userDTO.getUserName();
            row[2] = userDTO.getUserStatus();
            row[0] = userDTO.getUserId();
            tableModel.addRow(row);
        }

    }

    private void loadAllPrivileges() {
        List<UserPrivilegeDTO> userPrivilegeDTOList = UserController.allPrivileges();

        DefaultListModel defaultListModel = new DefaultListModel();

        for (UserPrivilegeDTO userPrivilegeDTO : userPrivilegeDTOList) {
            defaultListModel.addElement(userPrivilegeDTO.getPrivilege());
        }

        allPrivilegesList.setModel(defaultListModel);

    }

    private void clearPanelData() {

        useNameTextField.setText("");
        passwordField.setText("");
        rePasswordField.setText("");
        loadAllPrivileges();
    }

}
